# Generated by Django 5.0.6 on 2024-11-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='net_total',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='id',
            new_name='order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='No address provided', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='No address provided', max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='No address provided', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='No address provided', max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(default='No address provided', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_num',
            field=models.CharField(default='No address provided', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='No address provided', max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.CharField(default='No address provided', max_length=20),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
