# Generated by Django 5.0.6 on 2024-11-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_remove_payment_order_remove_shipping_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_num',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.CharField(max_length=20),
        ),
    ]
