# Generated by Django 5.0.6 on 2024-11-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_userreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='create_date',
            field=models.DateTimeField(default=(2024, 11, 4, 23, 40, 12, 0, 309, 0)),
        ),
        migrations.AddField(
            model_name='userreview',
            name='product_id',
            field=models.IntegerField(default=1),
        ),
    ]
