# Generated by Django 5.0.6 on 2024-11-04 20:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_userreview_create_date_userreview_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
