# Generated by Django 5.0.6 on 2024-11-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_userreview_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='product_id',
        ),
    ]
