# Generated by Django 5.0.6 on 2024-11-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_userreview_create_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
