# Generated by Django 5.0.6 on 2024-11-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_userreviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReviews',
        ),
    ]
