# Generated by Django 5.0.6 on 2024-11-09 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_userreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreview',
            options={},
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='review_text',
        ),
        migrations.AddField(
            model_name='userreview',
            name='email',
            field=models.EmailField(default=30, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreview',
            name='product_id',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreview',
            name='review',
            field=models.TextField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreview',
            name='review_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreview',
            name='star_reviews',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
